//! Audio subsystem driver for SF32LB52x
//!
//! Supports AUDPRC (digital audio processor) + AUDCODEC (analog codec) for
//! DAC output (Class-D PA) and ADC input (microphone recording).
//!
//! # Architecture
//!
//! ```text
//! DAC: DMA → AUDPRC TX_CH0 → AUDCODEC DAC → Class-D PA
//! ADC: ADCIN mic → AUDCODEC ADC → AUDPRC RX_CH0 → DMA
//! ```
//!
//! AUDPRC and AUDCODEC are connected via internal bus (`op_mode=0`), no external pins needed.
//!
//! # DAC Example (blocking)
//!
//! ```ignore
//! let mut dac = audio::AudioDac::new_blocking(
//!     p.AUDPRC,
//!     p.DMAC1_CH1,
//!     audio::DacConfig::default(),
//! );
//! dac.write_blocking(&samples);
//! ```
//!
//! # ADC Example (async, streaming)
//!
//! ```ignore
//! bind_interrupts!(struct Irqs {
//!     AUDPRC => audio::InterruptHandler;
//! });
//!
//! let mut adc = audio::AudioAdc::new(
//!     p.AUDPRC,
//!     p.DMAC1_CH2,
//!     Irqs,
//!     audio::AdcConfig::default(),
//! );
//!
//! let mut stream = adc.start_stream(&mut dma_buf);
//! loop {
//!     stream.read(&mut buf).await.unwrap();
//! }
//! ```

pub(crate) mod codec;
mod adc;
mod dac;

pub use adc::*;
pub use dac::*;

use embassy_hal_internal::Peripheral;

use crate::{interrupt, peripherals};

pub use crate::aud_pll::SampleRate;

/// Audio channel mode.
///
/// Determines how audio samples are packed in 32-bit FIFO entries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum ChannelMode {
    /// Each FIFO entry = one 16-bit sample (low 16 bits).
    Mono,
    /// Each FIFO entry = packed stereo pair `[R:hi16 | L:lo16]`.
    Stereo,
}

/// DAC output configuration.
#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct DacConfig {
    /// Sample rate (default: 48kHz).
    pub sample_rate: SampleRate,
    /// Channel mode (default: Stereo).
    pub channel_mode: ChannelMode,
    /// DAC path coarse volume, 0-15 (default: 6).
    pub volume: u8,
}

impl Default for DacConfig {
    fn default() -> Self {
        Self {
            sample_rate: SampleRate::Hz48000,
            channel_mode: ChannelMode::Stereo,
            volume: 6,
        }
    }
}

/// ADC input configuration.
#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct AdcConfig {
    /// Sample rate (default: 48kHz).
    pub sample_rate: SampleRate,
    /// Channel mode (default: Stereo).
    pub channel_mode: ChannelMode,
    /// ADC path coarse volume, 0-15 (default: 6, 0dB).
    pub volume: u8,
}

impl Default for AdcConfig {
    fn default() -> Self {
        Self {
            sample_rate: SampleRate::Hz48000,
            channel_mode: ChannelMode::Stereo,
            volume: 6,
        }
    }
}

/// Audio driver error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Error {
    /// DMA transfer error.
    Dma,
    /// FIFO overrun.
    Overrun,
}

// Instance trait for AUDPRC (singleton, needed for DMA trait system)
#[allow(private_interfaces)]
pub(crate) trait SealedInstance: crate::rcc::RccEnableReset {}

#[allow(private_bounds)]
pub trait Instance: Peripheral<P = Self> + SealedInstance + 'static + Send {
    #[doc(hidden)]
    type Interrupt: interrupt::typelevel::Interrupt;
}

impl SealedInstance for peripherals::AUDPRC {}

impl Instance for peripherals::AUDPRC {
    type Interrupt = crate::interrupt::typelevel::AUDPRC;
}

// DMA traits (implementations generated by build.rs from dma.yaml)
dma_trait!(TxCh0Dma, Instance);
dma_trait!(RxCh0Dma, Instance);
